### ISSUE TITLE
Dear author, I find the code seems to be invalid? The request is 500, but I use the browser to access normally, the account is normal, could you help me update

### ISSUE THREAD

**Issue by winie-hy** [AshwinPathi/claude-api-py#10]
Dear author, I find the code seems to be invalid? The request is 500, but I use the browser to access normally, the account is normal, could you help me update

**Comment by goodskillprogramer** [comment]
the response from the server is 500. It seems the server changed something .please help to release a new version.

**Comment by winie-hy** [comment]
I found that the normal conversation can still work, but the upload file conversation is invalid.

**Comment by winie-hy** [comment]
I am really stupid, the original file encoding problem, did not successfully deal with alsi encoding is empty resulting in failure

**Comment by AshwinPathi** [comment]
@winie-hy were you able to fix it? Could you be more specific about the issue, like does the `example.py` script not work?

**Comment by winie-hy** [comment]
I converted the txt files I uploaded to utf8 format to get the implementation, I think because of the system's sake, ubuntu can not recognize ansi encoding
