### ISSUE TITLE
Empty Response

### ISSUE THREAD

**Issue by pendekarcode** [AshwinPathi/claude-api-py#15]
![Screenshot 2023-08-10 10 39 16](https://github.com/AshwinPathi/claude-api-py/assets/52091445/d5ae95ae-1876-4be6-ac22-2129130af7b0)
Is anyone else going through this, or is it just me? It's been 2 days, and I haven't an empty response.

**Comment by AshwinPathi** [comment]
This is the same issue as https://github.com/AshwinPathi/claude-api-py/issues/14 I think, I'm fixing it now.

**Comment by AshwinPathi** [comment]
@pendekarcode just pushed a fix, try now. The completion field should be filled out now

**Comment by pendekarcode** [comment]
thank you for your support. update code is very useful. Thank you very much.
