### ISSUE TITLE
Hope to get your advice on the question

### ISSUE THREAD

**Issue by winie-hy** [AshwinPathi/claude-api-py#16]
Dear author, is it possible to implement asynchronously if I have multiple Sessionkeys? It seems that he is limited by the official single dialogue, can you give me some suggestions to increase his efficiency? Thank you ~

**Comment by AshwinPathi** [comment]
What type of API do you want to see? 

I don't really see an ergonomic way to allow this right now. The best way to do this would just be to create multiple "clients" with multiple session keys and swap those out. You can also switch conversation contexts to use different conversations. Yes the efficiency may be better with asynchronous, I am working on an implementation now.

**Comment by xRiddin** [comment]
we def need an asynchronous version of this, rn it's quite slow

**Comment by AshwinPathi** [comment]
@xRiddin yea I can work on this
