### ISSUE TITLE
This part of the code sometimes goes wrong, looks like it's returning a null value, right? Can you help fix him? 

### ISSUE THREAD

**Issue by winie-hy** [AshwinPathi/claude-api-py#17]
![image](https://github.com/AshwinPathi/claude-api-py/assets/59427119/78c4165b-8b0c-4328-8b3a-328b513fdc6b)
![image](https://github.com/AshwinPathi/claude-api-py/assets/59427119/aa019e9d-c3f6-4996-9709-885076508469)
This part of the code sometimes goes wrong, looks like it's returning a null value, right? Can you help fix him? I'll look at the root of the problem @AshwinPathi

**Comment by winie-hy** [comment]
![image](https://github.com/AshwinPathi/claude-api-py/assets/59427119/776ef0a6-76aa-4fb0-95fa-c6e3200a6d52)
？

**Comment by AshwinPathi** [comment]
I just put out a fix for this. Try it out again.

**Comment by winie-hy** [comment]
Thank you. You're the best
