### ISSUE TITLE
schema error

### ISSUE THREAD

**Issue by zenafey** [AshwinPathi/claude-api-py#8]
while trying to start new conv or send message code shows this error:
requests.exceptions.MissingSchema: Invalid URL '<http.client.HTTPResponse object at 0x0000022655E3E700>': No scheme supplied. Perhaps you meant https://<http.client.HTTPResponse object at 0x0000022655E3E700>?

title rename, org id functions work properly

**Comment by AshwinPathi** [comment]
@zenafey what version of python are you using?

**Comment by zenafey** [comment]
@AshwinPathi 3.8.10 and 3.11.3(tried both)

**Comment by zenafey** [comment]
i found where was error, you used response object instead of response.geturl(), but now another error appeared:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://claude.ai/api/append_message

![image](https://github.com/AshwinPathi/claude-api-py/assets/118455214/9681c7b5-a60f-4a34-b502-e74cabbb7407)

**Comment by zenafey** [comment]
Im so sorry bro, that was just my stupid mistake, i installed sseclient, not sseclient-py, after installing second one any errors gone! thnaks

**Comment by AshwinPathi** [comment]
@zenafey yep that'll do it 😅 . Plan is to make my own SSE library and make this have 0 dependencies soon. Thanks for debugging the issue!
